name: flutter_audiobooks
description: A cross-platform audiobook player application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.9.34
  audio_service: ^0.18.11
  file_picker: ^5.3.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  flutter_isolate: ^2.0.4
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.9
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  generate: true

isar_schema: true