name: flutbook
description: A cross-platform audiobook player application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  audio_service: ^0.18.11
  cupertino_icons: ^1.0.2
  file_picker: ^5.3.3
  flutter:
    sdk: flutter
  flutter_isolate: ^2.0.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  just_audio: ^0.9.34
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2


dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

isar_schema: true


# firebase_auth: ^4.15.3
  # cloud_firestore: ^4.13.6