name: flutbook
description: A cross-platform audiobook player application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  audio_service: ^0.18.18
  cloud_firestore: ^6.1.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.7
  file_picker: ^10.3.7
  firebase_auth: ^6.1.2
  flutter:
    sdk: flutter
  flutter_isolate: ^2.0.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  json_annotation: ^4.9.0
  just_audio: ^0.10.5
  path: ^1.9.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2


dev_dependencies:
  build_runner: ^2.6.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  isar_community_generator: ^3.3.0
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

isar_schema: true
